# Generated by Django 3.0.5 on 2020-05-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200510_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('HOSTER', 'HOSTER'), ('INNOVATOR', 'INNOVATOR'), ('REVIEWER', 'REVIEWER')], max_length=10, null=True),
        ),
    ]
