# Generated by Django 3.0.5 on 2020-05-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='challenge_image',
        ),
    ]
