# Generated by Django 3.0.5 on 2020-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_challenges_challenge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challenge_image',
            field=models.ImageField(null=True, upload_to='challenge-images'),
        ),
    ]
