# Generated by Django 3.0.5 on 2020-05-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenges_challenge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa1', models.TextField(max_length=100)),
                ('qa2', models.TextField(max_length=100)),
                ('qa3', models.TextField(max_length=100)),
                ('qa4', models.TextField(max_length=100)),
                ('qa5', models.TextField(max_length=100)),
                ('qa6', models.TextField(max_length=100)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenges')),
            ],
        ),
    ]
