# Generated by Django 3.0.5 on 2020-05-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenges_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSubmissionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria1', models.CharField(choices=[('2', '2'), ('4', '4')], max_length=10)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='challenges.Submission')),
            ],
        ),
    ]
