# Generated by Django 3.0.5 on 2020-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_reviewsubmissionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsubmissionscore',
            name='criteria2',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('10', '10'), ('20', '20')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='reviewsubmissionscore',
            name='criteria3',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('10', '10'), ('20', '20')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='reviewsubmissionscore',
            name='criteria4',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('10', '10'), ('20', '20')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='reviewsubmissionscore',
            name='criteria5',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('10', '10'), ('20', '20')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewsubmissionscore',
            name='criteria1',
            field=models.CharField(choices=[('0', '0'), ('2', '2'), ('4', '4'), ('6', '6'), ('10', '10'), ('20', '20')], default=0, max_length=10),
        ),
    ]
