# Generated by Django 3.0.5 on 2020-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20200521_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsubmissionscore',
            name='TotalScore',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
