# Generated by Django 3.0.5 on 2020-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_reviewsubmissionscore_totalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsubmissionscore',
            name='TotalScore',
            field=models.CharField(max_length=10),
        ),
    ]
