# Generated by Django 3.0.5 on 2020-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_submission_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='review_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('NOT_Completed', 'NOT_Completed')], default='NOT_Completed', max_length=20),
        ),
    ]
