# Generated by Django 3.0.5 on 2020-05-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_auto_20200521_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='review_status',
            field=models.CharField(choices=[('NOT_Completed', 'NOT_Completed'), ('Completed', 'Completed')], default='NOT_Completed', max_length=20),
        ),
    ]
