# Generated by Django 3.0.5 on 2020-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0021_auto_20200521_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='review_status',
            field=models.BooleanField(),
        ),
    ]
