# Generated by Django 3.0.5 on 2020-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0022_auto_20200521_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='review_status',
            field=models.CharField(choices=[('NOT_COMPLETED', 'NOT_COMPLETED'), ('COMPLETED', 'COMPLETED')], max_length=20),
        ),
    ]
