# Generated by Django 3.0.5 on 2020-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0023_auto_20200521_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='review_status',
            field=models.BooleanField(default=False),
        ),
    ]
