# Generated by Django 3.0.5 on 2020-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_auto_20200521_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsubmissionscore',
            name='tip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
