# Generated by Django 3.0.5 on 2020-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_reviewsubmissionscore_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
