# Generated by Django 3.0.5 on 2020-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0027_auto_20200526_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsubmissionscore',
            name='TotalScore',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
