# Generated by Django 3.0.5 on 2020-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0028_auto_20200526_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsubmissionscore',
            name='TotalScore',
            field=models.CharField(max_length=10),
        ),
    ]
